# Generated by Django 3.2 on 2023-01-07 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15)),
                ('description', models.TextField(max_length=1000)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.FloatField(default=0)),
                ('experience', models.IntegerField(default=1)),
            ],
        ),
    ]
