# Generated by Django 3.2 on 2023-01-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0004_auto_20230102_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
