# Generated by Django 3.2 on 2023-01-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0006_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='image',
            field=models.ImageField(default='', upload_to='jops/'),
            preserve_default=False,
        ),
    ]
