# Generated by Django 3.2 on 2023-01-03 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jop', '0011_apply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jop_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
